# Generated by Django 5.2.8 on 2025-11-19 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoia_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('primary_color', models.CharField(default='#1A0066', max_length=20)),
                ('welcome_message', models.TextField(default='Olá! 👋 Sou o assistente virtual da clínica. Como posso te ajudar hoje?')),
                ('treatments', models.TextField(default='Implantes, Clareamento, Ortodontia, Limpeza, Restaurações')),
                ('embed_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
