# Generated by Django 5.2.8 on 2025-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontoia_chat', '0002_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='clinic_avatars/'),
        ),
    ]
